version: '3.1'

services:

  data_science_container:
    image: butlerc9/air_quality_jupyter
    volumes:
      - .:/home/jovyan/work jupyter/datascience-notebook
    ports:
      - 8888:8888
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}